name: "finance-modelling"
services:
  finance-modelling:
    build: ./
    image: finance-modelling:latest
    volumes:
      - .:/src
    tty: true
    command: /bin/bash
    container_name: finance-modelling